<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-Irminsul-551cd0bf-ebc3-4c24-bdec-9a66b65e2be3</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Confluent.Kafka" Version="2.15.0" />
    <PackageReference Include="Dapper" Version="2.1.79" />
    <PackageReference Include="dbup-postgresql" Version="7.0.1" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
    <PackageReference Include="Npgsql" Version="10.0.3" />
    <PackageReference Include="protobuf-net" Version="3.2.56" />
	<PackageReference Include="Akasha.Contracts" Version="1.0.3" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="IntegrationTests\" />
    <Folder Include="Mappers\" />
  </ItemGroup>
</Project>
